# Generated by Django 6.1 on 2026-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='duration_unit',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
